In [1]:
# import dependecies 
import pandas as pd
import csv
import os

In [2]:
# creates path for csv datafile
file1= "phs_2019_stage_1.csv"
file2= "phs_2019_stage_2.csv"
file3= "phs_2019_stage_3.csv"
file4= "phs_2019_stage_4.csv"  
file5= "phs_2019_playoffs.csv"

In [3]:
# reads the csv and transforms it into a dataframe
overwatch_df_1 = pd.read_csv(file1)
overwatch_df_2 = pd.read_csv(file2)
overwatch_df_3 = pd.read_csv(file3)
overwatch_df_4 = pd.read_csv(file4)
overwatch_df_5 = pd.read_csv(file5)

In [4]:
complete_overwatch_df = overwatch_df_1.append([overwatch_df_2, overwatch_df_3, overwatch_df_4, overwatch_df_5])

In [ ]:
complete_overwatch_df

In [5]:
# drops the columns below
dropped_complete_overwatch_df = complete_overwatch_df.drop(columns=["pelstart_time", "map_name",  "map_type", "start_time"])

In [6]:
# Creates a list of the rows we would liek to keep
stats = ["All Damage Done", "Assists", "Average Time Alive", "Critical Hit Accuracy", "Damage - Weapon Primary",  "Damage - Weapon Secondary", "Damage Blocked", "Damage Done", "Damage Taken", "Deaths", "Eliminations", "Healing Done", "Multikills", "Primary Fire Accuracy", "Primary Fire Hits", "Secondary Fire Accuracy", "Secondary Fire Hits", "Time Alive", "Weapon Accuracy"]

In [7]:
# Drops the row names that aren't included in the the list
stats_df = dropped_complete_overwatch_df[dropped_complete_overwatch_df['stat_name'].isin(stats)]

In [8]:
# Displays new dataframe
stats_df

,match_id,stage,player,team,stat_name,hero,stat_amount
0,21211,Overwatch League Stage 1,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.193400
1,21211,Overwatch League Stage 1,Bdosin,London Spitfire,Assists,All Heroes,13.000000
2,21211,Overwatch League Stage 1,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.623574
5,21211,Overwatch League Stage 1,Bdosin,London Spitfire,Damage Done,All Heroes,9039.330256
6,21211,Overwatch League Stage 1,Bdosin,London Spitfire,Damage Taken,All Heroes,4192.611340
...,...,...,...,...,...,...,...
103931,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Eliminations,Ana,19.000000
103939,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Healing Done,Ana,10009.825090
103942,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Multikills,Ana,2.000000
103961,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Time Alive,Ana,765.860023
103971,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Weapon Accuracy,Ana,0.273504

In [59]:
stats_df["stat_name"].unique()

array(['All Damage Done', 'Assists', 'Average Time Alive', 'Damage Done',
       'Damage Taken', 'Deaths', 'Eliminations', 'Healing Done',
       'Multikills', 'Time Alive', 'Weapon Accuracy',
       'Critical Hit Accuracy', 'Damage - Weapon Primary',
       'Secondary Fire Accuracy', 'Damage Blocked',
       'Damage - Weapon Secondary', 'Primary Fire Accuracy',
       'Primary Fire Hits', 'Secondary Fire Hits'], dtype=object)

In [9]:
# Rounds the stat_amount to four decimal places
rounded_stats_df = stats_df.round({"stat_amount" : 4})

In [10]:
# displays new dataframe 
rounded_stats_df

,match_id,stage,player,team,stat_name,hero,stat_amount
0,21211,Overwatch League Stage 1,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.1934
1,21211,Overwatch League Stage 1,Bdosin,London Spitfire,Assists,All Heroes,13.0000
2,21211,Overwatch League Stage 1,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.6236
5,21211,Overwatch League Stage 1,Bdosin,London Spitfire,Damage Done,All Heroes,9039.3303
6,21211,Overwatch League Stage 1,Bdosin,London Spitfire,Damage Taken,All Heroes,4192.6113
...,...,...,...,...,...,...,...
103931,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Eliminations,Ana,19.0000
103939,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Healing Done,Ana,10009.8251
103942,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Multikills,Ana,2.0000
103961,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Time Alive,Ana,765.8600
103971,30157,Overwatch League 2019 Post-Season,Twilight,Vancouver Titans,Weapon Accuracy,Ana,0.2735

In [11]:
player_count_df = rounded_stats_df["stage"].nunique()
player_count_df

8

In [47]:
Hero_name = (['Zenyatta', 'McCree', 'Zarya', 'D.Va',
       'Wrecking Ball', 'Orisa', 'Reinhardt', 'Winston', 'LÃºcio',
       'Brigitte', 'Hanzo', 'Ana', 'Widowmaker', 'Doomfist', 'Tracer',
       'Soldier: 76', 'Sombra', 'Ashe', 'Mercy', 'Genji', 'Pharah',
       'Moira', 'TorbjÃ¶rn', 'Reaper', 'Mei', 'Bastion', 'Symmetra',
       'Roadhog', 'Junkrat', 'Baptiste', 'Sigma'])
Role =  (['Support', 'Damage', 'Tank', 'Tank',
       'Tank', 'Tank', 'Tank', 'Tank', 'Support',
       'Support', 'Damage', 'Support', 'Damage', 'Damage', 'Damage',
       'Damage', 'Damage', 'Damage', 'Support', 'Damage', 'Damage',
       'Support', 'Damage', 'Damage', 'Damage', 'Damage', 'Damage',
       'Tank', 'Damage', "Support", 'Tank'])

hero_role = pd.DataFrame({
    "hero" : Hero_name,
    "role" : Role
})
hero_role

             hero     role
0        Zenyatta  Support
1          McCree   Damage
2           Zarya     Tank
3            D.Va     Tank
4   Wrecking Ball     Tank
5           Orisa     Tank
6       Reinhardt     Tank
7         Winston     Tank
8           LÃºcio  Support
9        Brigitte  Support
10          Hanzo   Damage
11            Ana  Support
12     Widowmaker   Damage
13       Doomfist   Damage
14         Tracer   Damage
15    Soldier: 76   Damage
16         Sombra   Damage
17           Ashe   Damage
18          Mercy  Support
19          Genji   Damage
20         Pharah   Damage
21          Moira  Support
22       TorbjÃ¶rn   Damage
23         Reaper   Damage
24            Mei   Damage
25        Bastion   Damage
26       Symmetra   Damage
27        Roadhog     Tank
28        Junkrat   Damage
29       Baptiste  Support
30          Sigma     Tank

In [48]:

# Merge the hero class with the main dataframe
hero_class_df = (rounded_stats_df.merge(hero_role,on="hero",how="left"))

# Drop Nan values (All Heroes) from "hero" columns 
hero_class_df = hero_class_df[hero_class_df['role'].notna()]
print(hero_class_df.head(30))

    match_id                     stage    player             team  \
11     21211  Overwatch League Stage 1    Bdosin  London Spitfire
12     21211  Overwatch League Stage 1    Bdosin  London Spitfire
13     21211  Overwatch League Stage 1    Bdosin  London Spitfire
14     21211  Overwatch League Stage 1    Bdosin  London Spitfire
15     21211  Overwatch League Stage 1    Bdosin  London Spitfire
16     21211  Overwatch League Stage 1    Bdosin  London Spitfire
17     21211  Overwatch League Stage 1    Bdosin  London Spitfire
18     21211  Overwatch League Stage 1    Bdosin  London Spitfire
19     21211  Overwatch League Stage 1    Bdosin  London Spitfire
20     21211  Overwatch League Stage 1    Bdosin  London Spitfire
21     21211  Overwatch League Stage 1    Bdosin  London Spitfire
22     21211  Overwatch League Stage 1    Bdosin  London Spitfire
23     21211  Overwatch League Stage 1    Bdosin  London Spitfire
35     21211  Overwatch League Stage 1  Birdring  London Spitfire
36     21211  Overwatch League Stage 1  Birdring  London Spitfire
37     21211  Overwatch League Stage 1  Birdring  London Spitfire
38     21211  Overwatch League Stage 1  Birdring  London Spitfire
39     21211  Overwatch League Stage 1  Birdring  London Spitfire
40     21211  Overwatch League Stage 1  Birdring  London Spitfire
41     21211  Overwatch League Stage 1  Birdring  London Spitfire
42     21211  Overwatch League Stage 1  Birdring  London Spitfire
43     21211  Overwatch League Stage 1  Birdring  London Spitfire
44     21211  Overwatch League Stage 1  Birdring  London Spitfire
45     21211  Overwatch League Stage 1  Birdring  London Spitfire
46     21211  Overwatch League Stage 1  Birdring  London Spitfire
47     21211  Overwatch League Stage 1  Birdring  London Spitfire
48     21211  Overwatch League Stage 1  Birdring  London Spitfire
49     21211  Overwatch League Stage 1  Birdring  London Spitfire
50     21211  Overwatch League Stage 1  Birdring  London Spitfire
51     21211  Overwatch League Stage 1  Birdring  London Spitfire

                    stat_name      hero  stat_amount     role
11            All Damage Done  Zenyatta   14845.1934  Support
12                    Assists  Zenyatta      13.0000  Support
13         Average Time Alive  Zenyatta      87.6236  Support
14      Critical Hit Accuracy  Zenyatta       0.1479  Support
15    Damage - Weapon Primary  Zenyatta    6340.3303  Support
16               Damage Taken  Zenyatta    4192.6113  Support
17                     Deaths  Zenyatta       4.0000  Support
18               Eliminations  Zenyatta      18.0000  Support
19               Healing Done  Zenyatta   10225.9582  Support
20                 Multikills  Zenyatta       1.0000  Support
21    Secondary Fire Accuracy  Zenyatta       0.3135  Support
22                 Time Alive  Zenyatta     613.3650  Support
23            Weapon Accuracy  Zenyatta       0.3135  Support
35            All Damage Done    McCree    1439.9678   Damage
36                    Assists    McCree       1.0000   Damage
37         Average Time Alive    McCree      28.8260   Damage
38    Damage - Weapon Primary    McCree     683.1637   Damage
39  Damage - Weapon Secondary    McCree     283.0000   Damage
40               Damage Taken    McCree     648.3386   Damage
41                     Deaths    McCree       1.0000   Damage
42               Eliminations    McCree       1.0000   Damage
43    Secondary Fire Accuracy    McCree       0.4412   Damage
44                 Time Alive    McCree      57.6520   Damage
45            Weapon Accuracy    McCree       0.4412   Damage
46            All Damage Done     Zarya   18040.3536     Tank
47                    Assists     Zarya      10.0000     Tank
48         Average Time Alive     Zarya     139.5113     Tank
49    Damage - Weapon Primary     Zarya    3898.9106     Tank
50  Damage - Weapon Secondary     Zarya    6447.7777     Tank
51             Damage Blocked     Zarya    6013.1229     Tank

In [49]:
hero_picks = hero_class_df.drop_duplicates(subset=['match_id', 'hero'], keep='first')

In [50]:
hero_picks

,match_id,stage,player,team,stat_name,hero,stat_amount,role
11,21211,Overwatch League Stage 1,Bdosin,London Spitfire,All Damage Done,Zenyatta,14845.1934,Support
35,21211,Overwatch League Stage 1,Birdring,London Spitfire,All Damage Done,McCree,1439.9678,Damage
46,21211,Overwatch League Stage 1,Birdring,London Spitfire,All Damage Done,Zarya,18040.3536,Tank
72,21211,Overwatch League Stage 1,Fury,London Spitfire,All Damage Done,D.Va,13316.4290,Tank
84,21211,Overwatch League Stage 1,Fury,London Spitfire,Average Time Alive,Wrecking Ball,6.0960,Tank
...,...,...,...,...,...,...,...,...
464475,30157,Overwatch League 2019 Post-Season,Viol2t,San Francisco Shock,All Damage Done,Ana,3856.8818,Support
464485,30157,Overwatch League 2019 Post-Season,Viol2t,San Francisco Shock,All Damage Done,Baptiste,4603.0941,Support
464534,30157,Overwatch League 2019 Post-Season,moth,San Francisco Shock,Average Time Alive,Mercy,73.8903,Support
464587,30157,Overwatch League 2019 Post-Season,Haksal,Vancouver Titans,Average Time Alive,Genji,2.5960,Damage
464611,30157,Overwatch League 2019 Post-Season,JJANU,Vancouver Titans,All Damage Done,D.Va,394.2625,Tank

In [51]:
df = hero_class_df["match_id"].unique()
len(df)

319

In [52]:
hero_df = pd.DataFrame(hero_picks['hero'].value_counts())
hero_df = hero_df.rename(columns={"hero" : "Games Used"})

In [53]:
hero_df = hero_df.reset_index()

In [54]:
hero_df["Pick Rate"] = hero_df["Games Used"]/len(df)*100
hero_df

            index  Games Used   Pick Rate
0           LÃºcio         319  100.000000
1   Wrecking Ball         319  100.000000
2            D.Va         312   97.805643
3             Ana         307   96.238245
4          Tracer         304   95.297806
5        Zenyatta         302   94.670846
6          Sombra         297   93.103448
7      Widowmaker         295   92.476489
8         Winston         289   90.595611
9       Reinhardt         288   90.282132
10          Mercy         282   88.401254
11          Hanzo         268   84.012539
12       Brigitte         268   84.012539
13         Pharah         264   82.758621
14          Moira         258   80.877743
15          Orisa         257   80.564263
16          Zarya         252   78.996865
17       Doomfist         244   76.489028
18        Roadhog         227   71.159875
19       Baptiste         209   65.517241
20            Mei         208   65.203762
21         McCree         168   52.664577
22          Genji         164   51.410658
23        Bastion         152   47.648903
24       Symmetra         142   44.514107
25    Soldier: 76         141   44.200627
26         Reaper         141   44.200627
27        Junkrat         116   36.363636
28       TorbjÃ¶rn          68   21.316614
29           Ashe          51   15.987461
30          Sigma          18    5.642633

In [55]:
hero_df = hero_df.rename(columns={"index" : "hero"})
hero_df

             hero  Games Used   Pick Rate
0           LÃºcio         319  100.000000
1   Wrecking Ball         319  100.000000
2            D.Va         312   97.805643
3             Ana         307   96.238245
4          Tracer         304   95.297806
5        Zenyatta         302   94.670846
6          Sombra         297   93.103448
7      Widowmaker         295   92.476489
8         Winston         289   90.595611
9       Reinhardt         288   90.282132
10          Mercy         282   88.401254
11          Hanzo         268   84.012539
12       Brigitte         268   84.012539
13         Pharah         264   82.758621
14          Moira         258   80.877743
15          Orisa         257   80.564263
16          Zarya         252   78.996865
17       Doomfist         244   76.489028
18        Roadhog         227   71.159875
19       Baptiste         209   65.517241
20            Mei         208   65.203762
21         McCree         168   52.664577
22          Genji         164   51.410658
23        Bastion         152   47.648903
24       Symmetra         142   44.514107
25    Soldier: 76         141   44.200627
26         Reaper         141   44.200627
27        Junkrat         116   36.363636
28       TorbjÃ¶rn          68   21.316614
29           Ashe          51   15.987461
30          Sigma          18    5.642633

In [56]:
hero_pickrate = hero_role.merge(hero_df, how="outer", on="hero")
hero_pickrate

             hero     role  Games Used   Pick Rate
0        Zenyatta  Support         302   94.670846
1          McCree   Damage         168   52.664577
2           Zarya     Tank         252   78.996865
3            D.Va     Tank         312   97.805643
4   Wrecking Ball     Tank         319  100.000000
5           Orisa     Tank         257   80.564263
6       Reinhardt     Tank         288   90.282132
7         Winston     Tank         289   90.595611
8           LÃºcio  Support         319  100.000000
9        Brigitte  Support         268   84.012539
10          Hanzo   Damage         268   84.012539
11            Ana  Support         307   96.238245
12     Widowmaker   Damage         295   92.476489
13       Doomfist   Damage         244   76.489028
14         Tracer   Damage         304   95.297806
15    Soldier: 76   Damage         141   44.200627
16         Sombra   Damage         297   93.103448
17           Ashe   Damage          51   15.987461
18          Mercy  Support         282   88.401254
19          Genji   Damage         164   51.410658
20         Pharah   Damage         264   82.758621
21          Moira  Support         258   80.877743
22       TorbjÃ¶rn   Damage          68   21.316614
23         Reaper   Damage         141   44.200627
24            Mei   Damage         208   65.203762
25        Bastion   Damage         152   47.648903
26       Symmetra   Damage         142   44.514107
27        Roadhog     Tank         227   71.159875
28        Junkrat   Damage         116   36.363636
29       Baptiste  Support         209   65.517241
30          Sigma     Tank          18    5.642633

In [57]:
hero_pickrate = hero_pickrate.sort_values(by=['role', 'Pick Rate'], ascending=False)
hero_pickrate

             hero     role  Games Used   Pick Rate
4   Wrecking Ball     Tank         319  100.000000
3            D.Va     Tank         312   97.805643
7         Winston     Tank         289   90.595611
6       Reinhardt     Tank         288   90.282132
5           Orisa     Tank         257   80.564263
2           Zarya     Tank         252   78.996865
27        Roadhog     Tank         227   71.159875
30          Sigma     Tank          18    5.642633
8           LÃºcio  Support         319  100.000000
11            Ana  Support         307   96.238245
0        Zenyatta  Support         302   94.670846
18          Mercy  Support         282   88.401254
9        Brigitte  Support         268   84.012539
21          Moira  Support         258   80.877743
29       Baptiste  Support         209   65.517241
14         Tracer   Damage         304   95.297806
16         Sombra   Damage         297   93.103448
12     Widowmaker   Damage         295   92.476489
10          Hanzo   Damage         268   84.012539
20         Pharah   Damage         264   82.758621
13       Doomfist   Damage         244   76.489028
24            Mei   Damage         208   65.203762
1          McCree   Damage         168   52.664577
19          Genji   Damage         164   51.410658
25        Bastion   Damage         152   47.648903
26       Symmetra   Damage         142   44.514107
15    Soldier: 76   Damage         141   44.200627
23         Reaper   Damage         141   44.200627
28        Junkrat   Damage         116   36.363636
22       TorbjÃ¶rn   Damage          68   21.316614
17           Ashe   Damage          51   15.987461