In [13]:
# import dependecies 
import pandas as pd
import csv
import os

In [16]:
# creates path for csv datafile
file1= "phs_2019_stage_1.csv"
file2= "phs_2019_stage_2.csv"
file3= "phs_2019_stage_3.csv"
file4= "phs_2019_stage_4.csv"  
file5= "phs_2019_playoffs.csv"

In [17]:
# reads the csv and transforms it into a dataframe
overwatch_df_1 = pd.read_csv(file1)
overwatch_df_2 = pd.read_csv(file2)
overwatch_df_3 = pd.read_csv(file3)
overwatch_df_4 = pd.read_csv(file4)
overwatch_df_5 = pd.read_csv(file5)

In [21]:
complete_overwatch_df = overwatch_df_1.append([overwatch_df_2, overwatch_df_3, overwatch_df_4, overwatch_df_5])

In [24]:
complete_overwatch_df

,pelstart_time,match_id,stage,map_type,map_name,player,team,stat_name,hero,stat_amount,start_time
0,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.193400,NaN
1,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Assists,All Heroes,13.000000,NaN
2,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.623574,NaN
3,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Barrier Damage Done,All Heroes,5674.344475,NaN
4,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Damage - Quick Melee,All Heroes,78.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...
103967,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Ultimates Used,Ana,6.000000,9/29/2019 20:47
103968,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Unscoped Accuracy,Ana,0.528777,9/29/2019 20:47
103969,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Unscoped Hits,Ana,147.000000,9/29/2019 20:47
103970,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Unscoped Shots,Ana,278.000000,9/29/2019 20:47
103971,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Weapon Accuracy,Ana,0.273504,9/29/2019 20:47

In [42]:
# drops the columns below
dropped_complete_overwatch_df = complete_overwatch_df.drop(columns=["pelstart_time", "stage",  "match_id", "start_time"])

In [43]:
# Creates a list of the rows we would liek to keep
stats = ["All Damage Done", "Assists", "Average Time Alive", "Critical Hit Accuracy", "Damage - Weapon Primary",  "Damage - Weapon Secondary", "Damage Blocked", "Damage Done", "Damage Taken", "Deaths", "Eliminations", "Healing Done", "Multikills", "Primary Fire Accuracy", "Primary Fire Hits", "Secondary Fire Accuracy", "Secondary Fire Hits", "Time Alive", "Weapon Accuracy"]

In [44]:
# Drops the row names that aren't included in the the list
stats_df = dropped_complete_overwatch_df[dropped_complete_overwatch_df['stat_name'].isin(stats)]

In [46]:
# Displays new dataframe
stats_df

,map_type,map_name,player,team,stat_name,hero,stat_amount
0,CONTROL,Ilios,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.193400
1,CONTROL,Ilios,Bdosin,London Spitfire,Assists,All Heroes,13.000000
2,CONTROL,Ilios,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.623574
5,CONTROL,Ilios,Bdosin,London Spitfire,Damage Done,All Heroes,9039.330256
6,CONTROL,Ilios,Bdosin,London Spitfire,Damage Taken,All Heroes,4192.611340
...,...,...,...,...,...,...,...
103931,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Eliminations,Ana,19.000000
103939,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Healing Done,Ana,10009.825090
103942,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Multikills,Ana,2.000000
103961,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Time Alive,Ana,765.860023
103971,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Weapon Accuracy,Ana,0.273504

In [61]:
# Rounds the stat_amount to four decimal places
rounded_stats_df = stats_df.round({"stat_amount" : 4})

In [62]:
# displays new dataframe 
rounded_stats_df

,map_type,map_name,player,team,stat_name,hero,stat_amount
0,CONTROL,Ilios,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.1934
1,CONTROL,Ilios,Bdosin,London Spitfire,Assists,All Heroes,13.0000
2,CONTROL,Ilios,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.6236
5,CONTROL,Ilios,Bdosin,London Spitfire,Damage Done,All Heroes,9039.3303
6,CONTROL,Ilios,Bdosin,London Spitfire,Damage Taken,All Heroes,4192.6113
...,...,...,...,...,...,...,...
103931,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Eliminations,Ana,19.0000
103939,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Healing Done,Ana,10009.8251
103942,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Multikills,Ana,2.0000
103961,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Time Alive,Ana,765.8600
103971,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Weapon Accuracy,Ana,0.2735