In [1]:
# import dependecies 
import pandas as pd
import csv
import os

In [2]:
# creates path for csv datafile
file1= "phs_2019_stage_1.csv"
file2= "phs_2019_stage_2.csv"
file3= "phs_2019_stage_3.csv"
file4= "phs_2019_stage_4.csv"  
file5= "phs_2019_playoffs.csv"

In [3]:
# reads the csv and transforms it into a dataframe
overwatch_df_1 = pd.read_csv(file1)
overwatch_df_2 = pd.read_csv(file2)
overwatch_df_3 = pd.read_csv(file3)
overwatch_df_4 = pd.read_csv(file4)
overwatch_df_5 = pd.read_csv(file5)

In [4]:
complete_overwatch_df = overwatch_df_1.append([overwatch_df_2, overwatch_df_3, overwatch_df_4, overwatch_df_5])

In [5]:
complete_overwatch_df

,pelstart_time,match_id,stage,map_type,map_name,player,team,stat_name,hero,stat_amount,start_time
0,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.193400,NaN
1,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Assists,All Heroes,13.000000,NaN
2,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.623574,NaN
3,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Barrier Damage Done,All Heroes,5674.344475,NaN
4,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Damage - Quick Melee,All Heroes,78.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...
103967,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Ultimates Used,Ana,6.000000,9/29/2019 20:47
103968,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Unscoped Accuracy,Ana,0.528777,9/29/2019 20:47
103969,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Unscoped Hits,Ana,147.000000,9/29/2019 20:47
103970,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Unscoped Shots,Ana,278.000000,9/29/2019 20:47
103971,NaN,30157,Overwatch League 2019 Post-Season,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Weapon Accuracy,Ana,0.273504,9/29/2019 20:47

In [6]:
# drops the columns below
dropped_complete_overwatch_df = complete_overwatch_df.drop(columns=["pelstart_time", "stage",  "match_id", "start_time"])

In [7]:
# Creates a list of the rows we would liek to keep
stats = ["All Damage Done", "Assists", "Average Time Alive", "Critical Hit Accuracy", "Damage - Weapon Primary",  "Damage - Weapon Secondary", "Damage Blocked", "Damage Done", "Damage Taken", "Deaths", "Eliminations", "Healing Done", "Multikills", "Primary Fire Accuracy", "Primary Fire Hits", "Secondary Fire Accuracy", "Secondary Fire Hits", "Time Alive", "Weapon Accuracy"]

In [8]:
# Drops the row names that aren't included in the the list
stats_df = dropped_complete_overwatch_df[dropped_complete_overwatch_df['stat_name'].isin(stats)]

In [9]:
# Displays new dataframe
stats_df

,map_type,map_name,player,team,stat_name,hero,stat_amount
0,CONTROL,Ilios,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.193400
1,CONTROL,Ilios,Bdosin,London Spitfire,Assists,All Heroes,13.000000
2,CONTROL,Ilios,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.623574
5,CONTROL,Ilios,Bdosin,London Spitfire,Damage Done,All Heroes,9039.330256
6,CONTROL,Ilios,Bdosin,London Spitfire,Damage Taken,All Heroes,4192.611340
...,...,...,...,...,...,...,...
103931,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Eliminations,Ana,19.000000
103939,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Healing Done,Ana,10009.825090
103942,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Multikills,Ana,2.000000
103961,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Time Alive,Ana,765.860023
103971,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Weapon Accuracy,Ana,0.273504

In [10]:
# Rounds the stat_amount to four decimal places
rounded_stats_df = stats_df.round({"stat_amount" : 4})

In [11]:
# displays new dataframe 
rounded_stats_df

,map_type,map_name,player,team,stat_name,hero,stat_amount
0,CONTROL,Ilios,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.1934
1,CONTROL,Ilios,Bdosin,London Spitfire,Assists,All Heroes,13.0000
2,CONTROL,Ilios,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.6236
5,CONTROL,Ilios,Bdosin,London Spitfire,Damage Done,All Heroes,9039.3303
6,CONTROL,Ilios,Bdosin,London Spitfire,Damage Taken,All Heroes,4192.6113
...,...,...,...,...,...,...,...
103931,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Eliminations,Ana,19.0000
103939,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Healing Done,Ana,10009.8251
103942,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Multikills,Ana,2.0000
103961,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Time Alive,Ana,765.8600
103971,PAYLOAD,Watchpoint: Gibraltar,Twilight,Vancouver Titans,Weapon Accuracy,Ana,0.2735

In [12]:
Hero_name = (['Zenyatta', 'McCree', 'Zarya', 'D.Va',
       'Wrecking Ball', 'Orisa', 'Reinhardt', 'Winston', 'LÃºcio',
       'Brigitte', 'Hanzo', 'Ana', 'Widowmaker', 'Doomfist', 'Tracer',
       'Soldier: 76', 'Sombra', 'Ashe', 'Mercy', 'Genji', 'Pharah',
       'Moira', 'TorbjÃ¶rn', 'Reaper', 'Mei', 'Bastion', 'Symmetra',
       'Roadhog', 'Junkrat', 'Baptiste', 'Sigma'])
Role =  (['Support', 'Damage', 'Tank', 'Tank',
       'Tank', 'Tank', 'Tank', 'Tank', 'Support',
       'Support', 'Damage', 'Support', 'Damage', 'Damage', 'Damage',
       'Damage', 'Damage', 'Damage', 'Mercy', 'Damage', 'Damage',
       'Support', 'Damage', 'Damage', 'Damage', 'Damage', 'Damage',
       'Tank', 'Damage', "Support", 'Tank'])

hero_df = pd.DataFrame({
    "hero" : Hero_name,
    "role" : Role
})
hero_df

             hero     role
0        Zenyatta  Support
1          McCree   Damage
2           Zarya     Tank
3            D.Va     Tank
4   Wrecking Ball     Tank
5           Orisa     Tank
6       Reinhardt     Tank
7         Winston     Tank
8           LÃºcio  Support
9        Brigitte  Support
10          Hanzo   Damage
11            Ana  Support
12     Widowmaker   Damage
13       Doomfist   Damage
14         Tracer   Damage
15    Soldier: 76   Damage
16         Sombra   Damage
17           Ashe   Damage
18          Mercy    Mercy
19          Genji   Damage
20         Pharah   Damage
21          Moira  Support
22       TorbjÃ¶rn   Damage
23         Reaper   Damage
24            Mei   Damage
25        Bastion   Damage
26       Symmetra   Damage
27        Roadhog     Tank
28        Junkrat   Damage
29       Baptiste  Support
30          Sigma     Tank

In [16]:
# Merge the hero class with the main dataframe
hero_class_df = (rounded_stats_df.merge(hero_df,on="hero",how="left"))

# Drop Nan values (All Heroes) from "hero" columns 
hero_class_df = hero_class_df[hero_class_df['role'].notna()]
print(hero_class_df.head(30))

   map_type map_name    player             team                  stat_name  \
11  CONTROL    Ilios    Bdosin  London Spitfire            All Damage Done
12  CONTROL    Ilios    Bdosin  London Spitfire                    Assists
13  CONTROL    Ilios    Bdosin  London Spitfire         Average Time Alive
14  CONTROL    Ilios    Bdosin  London Spitfire      Critical Hit Accuracy
15  CONTROL    Ilios    Bdosin  London Spitfire    Damage - Weapon Primary
16  CONTROL    Ilios    Bdosin  London Spitfire               Damage Taken
17  CONTROL    Ilios    Bdosin  London Spitfire                     Deaths
18  CONTROL    Ilios    Bdosin  London Spitfire               Eliminations
19  CONTROL    Ilios    Bdosin  London Spitfire               Healing Done
20  CONTROL    Ilios    Bdosin  London Spitfire                 Multikills
21  CONTROL    Ilios    Bdosin  London Spitfire    Secondary Fire Accuracy
22  CONTROL    Ilios    Bdosin  London Spitfire                 Time Alive
23  CONTROL    Ilios    Bdosin  London Spitfire            Weapon Accuracy
35  CONTROL    Ilios  Birdring  London Spitfire            All Damage Done
36  CONTROL    Ilios  Birdring  London Spitfire                    Assists
37  CONTROL    Ilios  Birdring  London Spitfire         Average Time Alive
38  CONTROL    Ilios  Birdring  London Spitfire    Damage - Weapon Primary
39  CONTROL    Ilios  Birdring  London Spitfire  Damage - Weapon Secondary
40  CONTROL    Ilios  Birdring  London Spitfire               Damage Taken
41  CONTROL    Ilios  Birdring  London Spitfire                     Deaths
42  CONTROL    Ilios  Birdring  London Spitfire               Eliminations
43  CONTROL    Ilios  Birdring  London Spitfire    Secondary Fire Accuracy
44  CONTROL    Ilios  Birdring  London Spitfire                 Time Alive
45  CONTROL    Ilios  Birdring  London Spitfire            Weapon Accuracy
46  CONTROL    Ilios  Birdring  London Spitfire            All Damage Done
47  CONTROL    Ilios  Birdring  London Spitfire                    Assists
48  CONTROL    Ilios  Birdring  London Spitfire         Average Time Alive
49  CONTROL    Ilios  Birdring  London Spitfire    Damage - Weapon Primary
50  CONTROL    Ilios  Birdring  London Spitfire  Damage - Weapon Secondary
51  CONTROL    Ilios  Birdring  London Spitfire             Damage Blocked

        hero  stat_amount     role
11  Zenyatta   14845.1934  Support
12  Zenyatta      13.0000  Support
13  Zenyatta      87.6236  Support
14  Zenyatta       0.1479  Support
15  Zenyatta    6340.3303  Support
16  Zenyatta    4192.6113  Support
17  Zenyatta       4.0000  Support
18  Zenyatta      18.0000  Support
19  Zenyatta   10225.9582  Support
20  Zenyatta       1.0000  Support
21  Zenyatta       0.3135  Support
22  Zenyatta     613.3650  Support
23  Zenyatta       0.3135  Support
35    McCree    1439.9678   Damage
36    McCree       1.0000   Damage
37    McCree      28.8260   Damage
38    McCree     683.1637   Damage
39    McCree     283.0000   Damage
40    McCree     648.3386   Damage
41    McCree       1.0000   Damage
42    McCree       1.0000   Damage
43    McCree       0.4412   Damage
44    McCree      57.6520   Damage
45    McCree       0.4412   Damage
46     Zarya   18040.3536     Tank
47     Zarya      10.0000     Tank
48     Zarya     139.5113     Tank
49     Zarya    3898.9106     Tank
50     Zarya    6447.7777     Tank
51     Zarya    6013.1229     Tank